<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <!-- Packages-->
  <ItemGroup>
    <PackageReference Include="Defra.Livestock.Sdk.Api.Strategies.Abstractions" />
  </ItemGroup>

  <!-- Schema files configuration -->
  <ItemGroup>
    <None Include="TestFramework\Data\Soap\Schemas\File*.xsd" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="TestFramework\Data\Soap\Schemas\Embedded*.xsd" />
  </ItemGroup>
  
</Project>
